@host=https://localhost:7278

POST {{host}}/Members/Register
Content-Type: application/json

{
    "Name": "Sajal Ghimire",
    "Email": "sajaluj2@gmail.com",
    "Password": "12u2Fw#jbw",
    "CompanySpaceId": "d9a88bb0-828b-4da8-96f4-761966fc7495"
}