@host=https://localhost:7278

POST {{host}}/Members/Register
Content-Type: application/json

{
    "Name": "Sajal Ghimire",
    "Email": "sajaluj2@gmail.com",
    "Password": "12u2Fw#jbw",
    "CompanySpaceId": "39bf1eb9-16e2-4fcc-b9cd-f38fb76d3469"
}