@host=https://localhost:7278

POST {{host}}/Members/Register
Content-Type: application/json

{
    "Name": "Sajal Ghimire",
    "Email": "sajaluj2@gmail.com",
    "Password": "12u2Fw#jbw",
    "CompanySpaceId": "84e20be7-4af4-434b-842b-c642da7474d2"
}