@host=https://localhost:7278/posts
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI0MjY1ZTk0LThkZjktNDhlZi1hZGY3LWQ5NjllMjY0NDg2ZCIsIlNwYWNlSWQiOiJhM2Q3ZWRmYi1iNzkxLTQzMDktYjI2MC1jYzA0NDFjMzg4N2MiLCJleHAiOjE2OTcwMDQ4MjEsImlzcyI6IldvcmtXaGlzcGVyIiwiYXVkIjoiTWVtYmVyIn0.q_JuXh2yQI8jWarJNyY05fyE6GO5A7ag_IlAGzZPI8s
@postId=1a113bf1-644c-4880-a07e-4ea5d3bb1e70
@commentId=1f350831-34cd-4bef-9865-fe1651f2fe7f
POST {{host}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "This is title",
    "Body": "The body is a bit longer than the post. As it should be.",
    "IsPrivate": true
}

#########

POST {{host}}/{{postId}}/upvote
Authorization: Bearer {{token}}

#######

POST {{host}}/{{postId}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "CommentText": "h"
}

#######
GET {{host}}/{{postId}}
Authorization: Bearer {{token}}

#######
POST {{host}}/{{postId}}/{{commentId}}/upvote
Authorization: Bearer {{token}}

