@host=https://localhost:7278/posts
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA5MThhNDVlLWNjMDMtNGU2NC1iY2JiLTAzMTQ1NjAyZjZlMyIsIlNwYWNlSWQiOiI1Y2VlZjUyNC05MTJkLTRmNDctOGE1NC1lZTQ5NzU4ZTk2ODciLCJleHAiOjE2OTIyNzEwMTAsImlzcyI6IldvcmtXaGlzcGVyIiwiYXVkIjoiTWVtYmVyIn0.8L5wK8KXdpM9cairyum94xqfDQ67CCd2QPNZt7j-wiA
@postId=357e2378-180d-48ca-a3db-e131da78130f
@commentId=3fc86bc4-5c53-46af-b6c0-dae61996ef06

POST {{host}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "This is title",
    "Body": "The body is a bit longer than the post. As it should be.",
    "IsPrivate": true
}

#########

POST {{host}}/{{postId}}/upvote
Authorization: Bearer {{token}}

#######

POST {{host}}/{{postId}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "CommentText": "Second"
}

#######
GET {{host}}/{{postId}}
Authorization: Bearer {{token}}

#######
POST {{host}}/{{postId}}/{{commentId}}/upvote
Authorization: Bearer {{token}}

