@host=https://localhost:7278/posts
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImY2ZjFjZjc1LTBhY2YtNDBjZi1hZTUyLTgwZjJkMzhjYWNmYyIsIlNwYWNlSWQiOiI4NGUyMGJlNy00YWY0LTQzNGItODQyYi1jNjQyZGE3NDc0ZDIiLCJleHAiOjE2OTY5MTc0NTMsImlzcyI6IldvcmtXaGlzcGVyIiwiYXVkIjoiTWVtYmVyIn0.rST6VH-qMmt8vz8uAdOqwImFbFFJy8kSltnimLNjNmU
@postId=a6a15194-1431-4003-9355-8c201adf2dc1
@commentId=3fc86bc4-5c53-46af-b6c0-dae61996ef06

POST {{host}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "This is title",
    "Body": "The body is a bit longer than the post. As it should be.",
    "IsPrivate": true
}

#########

POST {{host}}/{{postId}}/upvote
Authorization: Bearer {{token}}

#######

POST {{host}}/{{postId}}/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "CommentText": "Second"
}

#######
GET {{host}}/{{postId}}
Authorization: Bearer {{token}}

#######
POST {{host}}/{{postId}}/{{commentId}}/upvote
Authorization: Bearer {{token}}

