@host=https://localhost:7278
@spaceId=84e20be7-4af4-434b-842b-c642da7474d2
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImY2ZjFjZjc1LTBhY2YtNDBjZi1hZTUyLTgwZjJkMzhjYWNmYyIsIlNwYWNlSWQiOiI4NGUyMGJlNy00YWY0LTQzNGItODQyYi1jNjQyZGE3NDc0ZDIiLCJleHAiOjE2OTY5MTc0NTMsImlzcyI6IldvcmtXaGlzcGVyIiwiYXVkIjoiTWVtYmVyIn0.rST6VH-qMmt8vz8uAdOqwImFbFFJy8kSltnimLNjNmU
POST {{host}}/Space/Create
Content-Type: application/json

{
    "Name": "WorkWhisperer"
}

###

GET {{host}}/Space/AllSpaces

###

GET {{host}}/Space/{{spaceId}}
Authorization: Bearer {{token}}