@host=https://localhost:7278
@spaceId=d9a88bb0-828b-4da8-96f4-761966fc7495
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI0MjY1ZTk0LThkZjktNDhlZi1hZGY3LWQ5NjllMjY0NDg2ZCIsIlNwYWNlSWQiOiJhM2Q3ZWRmYi1iNzkxLTQzMDktYjI2MC1jYzA0NDFjMzg4N2MiLCJleHAiOjE2OTcwMDQ4MjEsImlzcyI6IldvcmtXaGlzcGVyIiwiYXVkIjoiTWVtYmVyIn0.q_JuXh2yQI8jWarJNyY05fyE6GO5A7ag_IlAGzZPI8s

POST {{host}}/Space/Create
Content-Type: application/json

{
    "Name": "WorkWhisperer"
}

###

GET {{host}}/Space/AllSpaces

###

GET {{host}}/Space/{{spaceId}}
Authorization: Bearer {{token}}